astra_db:
  collection_name: "mySupportProject"

retriever:
  top_k: 10
  score_threshold: 0.7

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

llm:
  google:
    provider: "google"
    model_name: "gemini-1.5-flash"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

tools:
  tavily:
    max_results: 5